version: '3'
services:
  core:
    container_name: gerbera-core
    environment:
      - CORE_LAUNCH_CMD=${CORE_LAUNCH_CMD}
    build:
      context: ./gerbera-core
      args:
        CORE_GIT_CMD: ${CORE_GIT_CMD}
    ports:
      - "49152:49152"
      - "1900:1900/udp"
    volumes:
      - gerbera-media:/gerbera-media
      - gerbera-home:/gerbera-home
    depends_on:
      - media
      - home
  selenium-hub:
    image: selenium/hub:3.141.59-bismuth
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    container_name: node-chrome
    image: selenium/node-chrome:3.141.59-bismuth
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  media:
    container_name: gerbera-media
    build:
      context: ./gerbera-media
    volumes:
      - gerbera-media:/gerbera-media
  ui:
    build:
      context: ./gerbera-ui
      args:
        INT_GIT_CMD: ${INT_GIT_CMD}
    environment:
      - GERBERA_BASE_URL=http://gerbera-core:49152
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - UI_TEST_CMD=${UI_TEST_CMD}
      - UI_TEST_DATA=${UI_TEST_DATA}
      - SELENIUM_BROWSER=${SELENIUM_BROWSER}
    depends_on:
      - selenium-hub
      - chrome
      - core
  home:
    container_name: gerbera-home
    build:
      context: ./gerbera-home
    volumes:
      - gerbera-home:/gerbera-home
volumes:
  gerbera-media:
  gerbera-home:
