# Dockerfile for Gerbera UI Test
# Purpose: Run the UI tests to verify Gerbera Server container
# Created by: Eamonn Buss
# Created on: 11/18/2018

##--------------------------------------
## Start with NodeJS
##--------------------------------------
FROM node

##--------------------------------------
## Enable Ubuntu Repositories
##--------------------------------------
RUN apt-get install git

##--------------------------------------
## Download Gerbera Integration Project
##--------------------------------------
RUN git clone https://github.com/elmodaddyb/gerbera-integration.git
WORKDIR /gerbera-integration/ui-test
RUN npm install
