# Dockerfile for Gerbera UI Test
# Purpose: Run the UI tests to verify Gerbera Server container
# Created by: Eamonn Buss
# Created on: 11/18/2018

##--------------------------------------
## Start with NodeJS
##--------------------------------------
FROM node

##--------------------------------------
## Install Testing Tools
##--------------------------------------
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository main
RUN apt-get install -y git \
  wget \
  xvfb \
  vim

##--------------------------------------
## Install Google Chrome
##--------------------------------------
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
RUN apt-get update && apt-get install -y google-chrome-stable

##--------------------------------------
## Download Gerbera Integration Project
##--------------------------------------
RUN git clone https://github.com/elmodaddyb/gerbera-integration.git

##--------------------------------------
## Run the UI Testing
##--------------------------------------
WORKDIR /gerbera-integration/ui-test
#RUN npm install
#RUN export DISPLAY=:99.0
#RUN /usr/bin/Xvfb&
#RUN sleep 3
#RUN npm run test
EXPOSE 9515
