version: '3'
services:
  core:
    container_name: gerbera-core
    environment:
      - CORE_LAUNCH_CMD=${CORE_LAUNCH_CMD}
    build:
      context: ./gerbera-core
      args:
        CORE_GIT_CMD: ${CORE_GIT_CMD}
    ports:
      - "49152:49152"
      - "1900:1900/udp"
    volumes:
      - gerbera-media:/gerbera-media
      - gerbera-home:/gerbera-home
    depends_on:
      - media
      - home
  media:
    container_name: gerbera-media
    build:
      context: ./gerbera-media
    volumes:
      - gerbera-media:/gerbera-media
  upnp:
    build:
      context: ./gerbera-upnp
      args:
        INT_GIT_CMD: ${INT_GIT_CMD}
    environment:
      - GERBERA_BASE_URL=http://gerbera-core:49152
      - CORE_SERVER_UUID=${CORE_SERVER_UUID}
    depends_on:
      - core
  home:
    container_name: gerbera-home
    build:
      context: ./gerbera-home
    volumes:
      - gerbera-home:/gerbera-home
volumes:
  gerbera-media:
  gerbera-home:
