version: '3'
services:
  core:
    container_name: core
    build:
      context: .
      dockerfile: ./gerbera-core/Dockerfile.core
    ports:
      - "49152:49152"
  selenium-hub:
    image: selenium/hub:3.141.59-bismuth
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59-bismuth
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  ui:
    build:
      context: .
      dockerfile: ./gerbera-ui/Dockerfile.ui
    environment:
      - GERBERA_BASE_URL=http://core:49152
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    depends_on:
      - selenium-hub
      - chrome
      - core
