version: '3'
services:
  core:
    container_name: gerbera-core
    build:
      context: .
      dockerfile: ./gerbera-core/Dockerfile.core
    ports:
      - "49152:49152"
    volumes:
      - gerbera-media:/gerbera-media
      - gerbera-home:/gerbera-home
    depends_on:
      - media
      - home
  selenium-hub:
    image: selenium/hub:3.141.59-bismuth
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    container_name: node-chrome
    image: selenium/node-chrome:3.141.59-bismuth
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  media:
    container_name: gerbera-media
    build:
      context: .
      dockerfile: ./gerbera-media/Dockerfile.media
    volumes:
      - gerbera-media:/gerbera-media
  home:
    container_name: gerbera-home
    build:
      context: .
      dockerfile: ./gerbera-home/Dockerfile.home
    volumes:
      - gerbera-home:/gerbera-home
volumes:
  gerbera-media:
  gerbera-home:
