version: '3'
services:
  core:
    build:
      context: .
      dockerfile: Dockerfile.core
    ports:
      - "49152:49152"
  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    environment:
      - GERBERA_BASE_URL=http://core:49152
